### ISSUE TITLE
Encoding for Class pointers is incorrect

### ISSUE THREAD

**Issue by SSheldon** [SSheldon/rust-objc#1]
`encode::<*const Class>` gives `@`, but it should be `#`. This happens because a `Class` is `Message`, and any `Message` pointer is encoded as `@`.

**Comment by metajack** [comment]
Can you please publish a new objc now? We have several crates in Servo that depend on this fix and use cargo deps.

**Comment by SSheldon** [comment]
Hey @metajack, the PR for libc 0.2 support was #30. Unfortunately I didn't have my laptop with me tonight but I'll be able to publish a new version tomorrow.

**Comment by SSheldon** [comment]
Sorry for the blocker!
