### ISSUE TITLE
Get Object from Class?

### ISSUE THREAD

**Issue by mikeumus** [SSheldon/rust-objc#106]
Hi @SSheldon 👋😀,

Thanks for this awesome library! I'd sponsor it if you turned on GitHub Sponsors 💖
Also, GitHub Discussion is a nice feature and would probably be better for the question I'm asking here:

Can you get an `Object` from a `Class` or can you only go the other direction? 

Thank you, 🙇🏻‍♂️

**Comment by madsmtm** [comment]
You can't really, since there is not a one-to-one relationship between these two. An object has one class, but a class can have many objects (called instances).

You can however create a _new_ object from a class by simply sending `new` to the class, if that's what you're asking:
```rust
let cls = class!(NSObject);
let obj: Object = msg_send![cls, new];
```
