### ISSUE TITLE
Core_Intrinsics no longer compiling

### ISSUE THREAD

**Issue by A-Helberg** [SSheldon/rust-objc#109]
If I copy the example.rs file to an external clean project (as main.rs) and try to run it, I get this:
```
error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/macros.rs:1:5
  |
1 | use std::intrinsics::ptr_guaranteed_eq;
```

I can't seem to find the offending use statement in the code on GH, so I am obviously missing something.
The fix however seems to be to add `#![feature(core_intrinsics)]` in lib.rs, but then requires the nightly toolchain

**Comment by madsmtm** [comment]
Huh, that's very odd, can you try running the following and post the output, just to see what's actually in the top of that file:
```sh
head ~/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/macros.rs
```

Also, can you post more information on your `Cargo.toml`, your toolchain, and your operating system? It sounds more likely that it's an issue with one of these things.

**Comment by A-Helberg** [comment]
Thanks for the reply 🙏 

Sure thing, but before your comment though I cleaned up all my deps to see if it's something on my machine.
I guess I screwed the deps up somehow, because the error is different now.

This is what was in macros.rs
```
use std::intrinsics::ptr_guaranteed_eq;
use runtime::Class;
/**
Gets a reference to a `Class`.

Panics if no class with the given name can be found.
To check for a class that may not exist, use `Class::get`.

# Example
```
After cleaning the deps, those top two lines are no longer there.
I think we can close this as it's obviously something I am doing wrong/messed up.
