### ISSUE TITLE
How to use callback functions?

### ISSUE THREAD

**Issue by yyon** [SSheldon/rust-objc#118]
Hello,
I'm trying to call a function in ObjC that takes a callback function, and I'm hoping to have that call back to a rust function. The function I'm trying to call is this one: [https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc](https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc).

When I pass null to the callback function, it works:
```
            let callback_pointer = std::ptr::null::<*const std::ffi::c_void>(); // *const *const core:ffi::c_void
            let _: id = objc::msg_send![controller, evaluateJavaScript:javascript_string completionHandler:callback_pointer];
            
```
I tried this:

```
> struct NSError(id);
> extern fn javascript_callback_macos(value: id, error: NSError) {
>     println!("javascript_callback_macos");
> }
> ...
> let _: id = objc::msg_send![controller, evaluateJavaScript:javascript_string completionHandler:javascript_callback_macos as extern fn(id, NSError)];
```

but it crashes without an error message

**Comment by madsmtm** [comment]
I've received a very similar question over here https://github.com/madsmtm/objc2/issues/269, you can probably adapt the answer to your use-case (if not, please do say so, then I'd be happy to provide more details).

**Comment by yyon** [comment]
That worked, thanks so much for your help! I don't know about objective C, so I didn't realize they were blocks and not functions.
