### ISSUE TITLE
How can I just execute a function?

### ISSUE THREAD

**Issue by gfetco** [SSheldon/rust-objc#33]
CGError CGWarpMouseCursorPosition ( CGPoint newCursorPosition );

I just want to execute this, with this library. Can you give me an example?

**Comment by SSheldon** [comment]
Hey @gfetco, this library would be used for calling Objective-C methods; what you've got there is a C function, so this library wouldn't be of any help.

That said, looks like this function is defined by the [core-graphics](https://github.com/servo/core-graphics-rs) crate, so you could execute that function like:
``` rust
extern crate core_graphics;

use core_graphics::display::CGWarpMouseCursorPosition;
use core_graphics::geometry::CGPoint;

fn main() {
    unsafe {
        let err = CGWarpMouseCursorPosition(CGPoint { x: 0.0, y: 0.0 });
    }
}
```

Good luck!

**Comment by gfetco** [comment]
Thank you, that's exactly what I ended up using yesterday! :)
