### ISSUE TITLE
How to implement a selector for a menuitem?

### ISSUE THREAD

**Issue by jmquigs** [SSheldon/rust-objc#41]
Hello, 

I'm trying to add a selector for a menuitem command.  Basically I have this:

```rust
let itemtitle = NSString::alloc(nil).init_str("PREFS");
let no_key = NSString::alloc(nil).init_str("");
let action = sel!(myhandler);
let item = NSMenuItem::alloc(nil).initWithTitle_action_keyEquivalent_(itemtitle, action, no_key);
menu.addItem_(item);
```

The menu works, but the item is disabled, which I think is because my object does not respond to the "myhandler" selector.  I'm not quite sure how to use this API to add one.  I tried implementing a custom object for the selector based on this example (https://github.com/SSheldon/rust-objc-foundation/blob/master/examples/custom_class.rs#L34), but it has no effect; I guess that is because I am defining the selector on "MYObject" and not the menu item.  Is this kind of selector implementation supported by the library at the moment?

**Comment by ngrewe** [comment]
I'm on mobile, so I can't exactly check right now, but it looks like you are not setting the target (i.e. the object the selector should be invoked on) for the menu item. 

Cheers,

Niels

**Comment by SSheldon** [comment]
Hey @jmquigs, I think @ngrewe's right, looks like you'll need to allocate an instance of your custom object and set it as the target of the item, like:
``` rust
let _: () = msg_send![item, setTarget:my_object];
```

Good luck!

**Comment by jmquigs** [comment]
Thanks @SSheldon, @ngrewe, that worked.
