### ISSUE TITLE
Example for calling methods with a block as a param?

### ISSUE THREAD

**Issue by alexkehayias** [SSheldon/rust-objc#50]
I'm working on a project that interops with Objective C and got stuck on figuring out how to pass a block [0] as a param to a method. As the comment in `cocoa-rs` mentions, I am "unsure how to bind to blocks" [1]. I think the next step is looking at how PyObjC implements this and finding a solution for rust. I got as far as reading through the Objective C docs to realize it is an object, but unclear how it is constructed, or invoked. Any ideas or things I should read to try and implement this?

[0] https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html
[1] https://github.com/servo/cocoa-rs/blob/master/src/appkit.rs#L2265

**Comment by alexkehayias** [comment]
Sorry I just found the rust-blocks crate. Closing!

**Comment by SSheldon** [comment]
Hey @alexkehayias, yep the `block` crate should help here :) If you want an example, you can see how I used it to create and pass a block to `-[NSData initWithBytesNoCopy:length:deallocator:]` in the `objc-foundation` crate: https://github.com/SSheldon/rust-objc-foundation/blob/0.1.1/src/data.rs#L42-L47
