### ISSUE TITLE
Id<Object> and friends are unsound and trigger undefined behaviour

### ISSUE THREAD

**Issue by nox** [SSheldon/rust-objc#57]
The type `Id<Object>` implements `Deref` and `DerefMut`, returning references of type `Object`. `Object` is defined as an opaque empty enum:

```rust
pub struct Object {
    _priv: PrivateMarker,
}
enum PrivateMarker { }
```

This is unsound, and may make rustc produce wildly different results in the future. At no point should anyone have a reference to a type that is uninhabited.

**Comment by SSheldon** [comment]
Hey @nox, any suggestions on alternative ways to declare a zero-sized type that is `repr(C)` and can't be created on the stack? Maybe a `PhantomData` field, but I had thought that made it not `repr(C)`.

**Comment by ubolonton** [comment]
I think we can do this:
```rust
pub struct Object {
    _priv: [u8; 0]
}
```
Since the field is not `pub`, the struct cannot be created outside of the module.

**Comment by SSheldon** [comment]
Thanks @ubolonton, `[u8; 0]` seems to do the trick!

`PhantomData` did not work, resulting in this warning:
> not FFI-safe: composed only of PhantomData
