### ISSUE TITLE
Using objc-encode crate?

### ISSUE THREAD

**Issue by ubolonton** [SSheldon/rust-objc#63]
This seems to be a improved version of objc type encoding: https://github.com/SSheldon/rust-objc-encode.

Is there a plan to switch to that?

**Comment by SSheldon** [comment]
Hey @ubolonton! I had prototyped a switch in c2ec92a, but the ergonomics aren't great until #52 is done, and it's a breaking change. So it's mostly just sitting around on hold indeterminately 😛

**Comment by SSheldon** [comment]
Ah sorry for dropping off! But yeah, I meant I wanted to make sure I had the best possible API before subjecting users to a breaking change. And with some new feature in rust, a much better way to handle this did arise :)

At this point I'm confident with the `objc-encode` API and there are some other breaking changes I want for `objc` (updating to rust 2018), so on master I've updated to use `objc-encode` in 6092caa.

**Comment by ubolonton** [comment]
Awesome! I hope it will be released soon :)
