### ISSUE TITLE
Class properties support?

### ISSUE THREAD

**Issue by 4lex1v** [SSheldon/rust-objc#70]
Hi!
I'm not very knowledgeable of Objective-C runtime and language in general, so I might be simply missing something. I was trying to write something like this in Rust using https://github.com/servo/core-foundation-rs:

```
CGContextRef gctx = [[NSGraphicsContext currentContext] CGContext];
```

It fails at runtime, I've started digging this and it looks like the `currentContext` is a class property, which to my understanding is not supported by this create. Source code has mentions nothing about class properties and as far as I understand it's a separate beast from `Ivar`. 

Am I right? If so would adding the support for this would be as straightforward as an Ivar and other structs?

**Comment by SSheldon** [comment]
Hey @4lex1v, any more details on how this fails at runtime?

It should be totally doable with the objc crate. You're right that we don't currently include functionality like `class_getProperty`, `property_getName`, etc, but those are only used for inspecting what properties are available on a class and getting metadata about them. If you want to access the value of a property, Objective-C does that with getter & setter methods using normal message sending. For example, a property named `foo` boils down to a getter method named `foo` and a setter method named `setFoo:`.

The property that Objective-C code accesses could be accessed from Rust like:
``` rust
let current: id = msg_send![class!(NSGraphicsContext), currentContext];
let gctx: CGContextRef = msg_send![current, CGContext];
```

**Comment by SSheldon** [comment]
Sorry, I misread some of your question and just realized you're asking specifically about class properties (not instance properties). I removed part of my other comment that's not as relevant.

That said, I don't think that should change much; afaik, accessing class properties is still done through message sending just like instance properties 😊

**Comment by 4lex1v** [comment]
After digging this further it seems it was the bug in my code and at the point of this call the value was indeed `Null`. I'll close this one, thanks for a fast response 👍
