### ISSUE TITLE
Trouble using CWWiFiClient from CoreWLAN

### ISSUE THREAD

**Issue by SirWindfield** [SSheldon/rust-objc#84]
I am having troubles using the CWWiFiClient interface from the CoreWLAN framework. The doc declare the type as `@interface CWWiFiClient : NSObject`, with `+ (CWWiFiClient *)sharedWiFiClient;` for accessing the global instance.
I am using the following code to obtain an instance, but it fails with `Class with name CWWiFiClient could not be found`:

```rust
type id = *mut Object;

pub trait CWWiFiClient : Sized {
    unsafe fn sharedWiFiClient(_: Self) -> id {
        msg_send![class!(CWWiFiClient), sharedWiFiClient]
    }

    unsafe fn interface() -> id;
}

impl CWWiFiClient for id {
    unsafe fn interface() -> id {
        // omitted for example, same goes for impl CWInterface which is returned by this method.
    }
}

pub fn CWWiFiClient() -> id {
    unsafe {
        msg_send!(class!(CWWiFiClient), sharedWiFiClient)
    }
}

fn main() {
    let _ = CWWiFiClient();
}
```

Any idea why this doesn't work? Relevant documentation: https://developer.apple.com/documentation/corewlan/cwwificlient?language=objc

**Comment by SSheldon** [comment]
@SirWindfield you probably can't just refer to the classes, I reckon you'll also need to make sure CoreWLAN is linked from your rust binary. Something like this: https://github.com/SSheldon/rust-uikit/blob/0.0.2/src/lib.rs#L23-L24

Sorry, I'm not familiar with CoreWLAN and it sounds like there's nothing specific to the objc crate here. Good luck!
