### ISSUE TITLE
It seems that version 0.2.7 breaks some builds

### ISSUE THREAD

**Issue by omni-viral** [SSheldon/rust-objc#86]
Just look at error [here](https://travis-ci.org/gfx-rs/gfx/jobs/599833168)

**Comment by SSheldon** [comment]
@omni-viral apologies! This means that code is unsound and will experience undefined behavior in an upcoming version of rust. I tried to address all the cases I could find before releasing, but wanted to make sure no one unknowingly experiences the undefined behavior.

For more info, check out #62 and the comments of rust-lang/rust#65355.

**Comment by omni-viral** [comment]
@SSheldon I see.
I guess `let () = ` will do the trick.

**Comment by SSheldon** [comment]
This is being fixed for gfx in gfx-rs/gfx#3050.
