### ISSUE TITLE
How do I call a class function?

### ISSUE THREAD

**Issue by LoganDark** [SSheldon/rust-objc#92]
I'm trying to call [NSFont.boldSystemFont](https://developer.apple.com/documentation/appkit/nsfont/1533549-boldsystemfont), but I can't figure out how. This doesn't work (`size` is a `*mut NSObject`):

```rust
let font: *mut Object = msg_send![class!(NSFont), boldSystemFont:size];
```

Or this:

```rust
let font: *mut Object = msg_send![class!(NSFont), boldSystemFont(size)];
```

Or this:

```rust
let font: *mut Object = msg_send![class!(NSFont), boldSystemFont, ofSize:size];
```

Or this:

```rust
let font: *mut Object = msg_send![class!(NSFont), boldSystemFont:, ofSize:size];
```

Or this:

```rust
let font: *mut Object = msg_send![class!(NSFont), boldSystemFont:ofSize:size];
```

Or this:

```rust
let font: *mut Object = msg_send![class!(NSFont), ofSize:size];
```

Or this:

```rust
let nsfont = class!(NSFont);
let method = nsfont.instance_method(sel!(boldSystemFont)).unwrap();
let font: *mut Object = msg_send![method, ofSize:size];
```

Or this:

```rust
let method = sel!(NSFont.boldSystemFont);
let font: *mut Object = msg_send![method, ofSize:size];
```

Or this:

```rust
let class = class!(NSFont);
let method = sel!(boldSystemFont:);
let font: *mut Object = class.send_message(method, size).unwrap();
```

I feel like I've tried everything, but this is just so _basic_ that `objc` MUST have functionality for it somewhere... right?

Please help me, I've spent way too much time trying to figure this out... That's not even everything I tried, but I don't want to make this issue any longer!

**Comment by SSheldon** [comment]
@LoganDark you need to switch that docs page to the Objective-C language: https://developer.apple.com/documentation/appkit/nsfont/1533549-boldsystemfontofsize?language=objc

Then you'll see that the method name in Objective-C is `boldSystemFontOfSize:`. So the code you'd want is something like:
```
let font: *mut Object = msg_send![class!(NSFont), boldSystemFontOfSize:size];
```

**Comment by LoganDark** [comment]
Oh, thank you! :D

**Comment by SSheldon** [comment]
> `size` is a `*mut NSObject`

Also, unless that was a typo, you'll see in the method signature that `size` should be a `CGFloat` rather than an object.

**Comment by LoganDark** [comment]
Huh, I assumed all things in Objective-C were objects... this is my first day D:

`objc` doesn't provide a CGFloat type, is there an equivalent in Rust (like is it just an `f32`?) or anything?

Also where should I go in the future to get help on this? I don't like having to bother the repository owner for help, you probably have way better things to do :p

Edit: Seems like specifying `f32` *or* `f64` as the return type both work... the docs say it's a double on 64-bit architectures so I guess I'm gonna do `f64`.
