### ISSUE TITLE
How to interact with list in the parameter

### ISSUE THREAD

**Issue by dzhou121** [SSheldon/rust-objc#94]
Hi,

I'm struggling to translate this objc method into rust:

- (void)getRectsBeingDrawn:(const NSRect * _Nullable *)rects 
                     count:(NSInteger *)count;
https://developer.apple.com/documentation/appkit/nsview/1483772-getrectsbeingdrawn?language=objc

**Comment by SSheldon** [comment]
The first argument would have to be `*mut *const NSRect`, and the second would be `*mut NSInteger`. `objc` doesn't provide those types, so you'll need them from another crate. Hope you were able to get this working!
